### ISSUE TITLE
Read me updation and making read me more presentable

### ISSUE THREAD

**Issue by JigarJoshi04** [JigarJoshi04/Calculator#10]

**Comment by sovetw** [comment]
Hi Jigar Joshi, I would like to work on the Readme.

**Comment by JigarJoshi04** [comment]
@sovetw  please go ahead with this.

**Comment by SanjayMarreddi** [comment]
Hey @JigarJoshi04  Is this still active? I can work on this ! Can you assign this to me ?

**Comment by JigarJoshi04** [comment]
@SanjayMarreddi I am assigning this to you. Please do help us with readme. I'll change the assignee. Thanks.

**Comment by SanjayMarreddi** [comment]
@JigarJoshi04  I will update this README file within 2 hours. Mean while you can add **hacktoberfest** label to this Issue !

**Comment by JigarJoshi04** [comment]
thank you @SanjayMarreddi
