### ISSUE TITLE
Updation of readme is required.

### ISSUE THREAD

**Issue by JigarJoshi04** [JigarJoshi04/Calculator#27]

**Comment by iamjmat** [comment]
@JigarJoshi04 Update of the functionalities is the only major change right ?  Any more to be done

**Comment by JigarJoshi04** [comment]
@iamjmat  yeah only functionalities are to be added.
Do try to make it more presentable if possible.
Updation of functionalities is the only major change.

**Comment by iamjmat** [comment]
Ok. I will create a PR for it .
